In [2]:
#Question 1
#statistics module. It provides some functions for calculating basic statistics on data like mean, median
import statistics

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
#sort() function to sort the list and min(),max() to find minimum and maximum values of list respectively.
ages.sort()
print("Sorted ages: ", ages)
print("Minimum value of ages: ", min(ages))
print("Maximum value of ages: ", max(ages))
# insert(position, value) - inserts the value in list at specified position
ages.insert(0,min(ages))
# append(value) - appends the value at the end of list
ages.append(max(ages))
print("List after update: ", ages)
#The biggest advantage of using median() function is that the data-list does not need to be sorted 
#before being sent as parameter to the median() function using statistice module
print("Median of ages: ", statistics.median(ages))
print("Average of ages: ", statistics.mean(ages))
print("Range of ages: ", max(ages)-min(ages))

# we can also use below code to find median and average of listed data
# ages_length = len(ages)
# if ages_length/2 != 0:
#     print('Median of ages: ', ages[int(ages_length/2)])
# else:
#     print('Median of ages: ', ages[ages_length-1/2]+ages[ages_length+1/2])   
# print('Average of ages: ', sum(ages)/ages_length)

Sorted ages:  [19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
Minimum value of ages:  19
Maximum value of ages:  26
List after update:  [19, 19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 26]
Median of ages:  24.0
Average of ages:  22.75
Range of ages:  7


In [4]:
#Question 2
dog= dict()
#update() method inserts the specified dictionary  or any key-value pairs to the resp. dictionary
dog.update({"name":"oreo", "color":"white", "breed":"shihzu", "legs":4, "age":2})
print("Added key-value pair to dog: ",dog)

#used  dict() function which creates a empty dictionary
student_dict = dict()
keyList = ["first_name", "last_name", "gender","age","marital status","skills","country","city","address"]
#added only keys to the dictionary with None value using update method
student_dict.update({key: None for key in keyList})
print("\nStudent_Dictionary after adding keys: ",student_dict)

#utilised len(dictionary) function to calculate lenght
print("Length of Student_Dictionary: ", len(student_dict))
#updated student_dict with sample values
student_dict.update({"first_name": "Surya", "last_name": "reddy", "gender": "Male", "age": "26",
                     "marital status": "Single", "skills": ["Java","Python"], "country": "India", "city": "Nellore",
                     "address": "6C ABC Street"})

print("\nStudent_dict ", student_dict)

#accessing paritcular value of key in dict: dict["key"]
print("\nAccessing Skills value in dictionary: ",student_dict["skills"])
#type(value) - function gives the datatype of provided values
print("Data Type of Skills in Student Dict: ", type(student_dict["skills"]))

#The extend() adds all the elements of an iterable (list, tuple, string etc.) to the end of the list
student_dict["skills"].extend(["Apex", "JavaScript"])
print("Updated Skills list after adding new values: ", student_dict["skills"])

# dict.keys() and values() gives the list of keys and values as a list respectively
print("\n",student_dict.keys())
print(student_dict.values())


Added key-value pair to dog:  {'name': 'oreo', 'color': 'white', 'breed': 'shihzu', 'legs': 4, 'age': 2}

Student_Dictionary after adding keys:  {'first_name': None, 'last_name': None, 'gender': None, 'age': None, 'marital status': None, 'skills': None, 'country': None, 'city': None, 'address': None}
Length of Student_Dictionary:  9

Student_dict  {'first_name': 'Surya', 'last_name': 'reddy', 'gender': 'Male', 'age': '26', 'marital status': 'Single', 'skills': ['Java', 'Python'], 'country': 'India', 'city': 'Nellore', 'address': '6C ABC Street'}

Accessing Skills value in dictionary:  ['Java', 'Python']
Data Type of Skills in Student Dict:  <class 'list'>
Updated Skills list after adding new values:  ['Java', 'Python', 'Apex', 'JavaScript']

 dict_keys(['first_name', 'last_name', 'gender', 'age', 'marital status', 'skills', 'country', 'city', 'address'])
dict_values(['Surya', 'reddy', 'Male', '26', 'Single', ['Java', 'Python', 'Apex', 'JavaScript'], 'India', 'Nellore', '6C ABC Street']

In [3]:
#Question 3
sisters = ("kavya","divya")
print("Sisters: ", sisters,)
brothers = ("Surya","shashi","Pavan")
print("Brothers: ", brothers)
siblings = sisters+brothers
print("siblings: ",siblings)
print("Number of Siblings:", len(siblings))
family_members = siblings+("krishna","Sandhya")
print("family_members: ", family_members)

Sisters:  ('kavya', 'divya')
Brothers:  ('Surya', 'shashi', 'Pavan')
siblings:  ('kavya', 'divya', 'Surya', 'shashi', 'Pavan')
Number of Siblings: 5
family_members:  ('kavya', 'divya', 'Surya', 'shashi', 'Pavan', 'krishna', 'Sandhya')


In [5]:
#Question 4
it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
print("Length of Set it_companies:",len(it_companies))
#add(elements) adds elements into the set
it_companies.add('Twitter')
print("it_companies: ", it_companies)
it_companies.update(['Cognizant','LinkedIn','Salesforce','Wipro'])
print("it_companies after update: ",it_companies)
#remove() remove the element from the set
it_companies.remove("LinkedIn")
print(it_companies)

#Difference between remove and discard
print("\nDifference between Remove() and Discard(): Discard() method is different from the remove() method, because the remove() method will throw an error if the specified item is not present in list, whereas the discard() method will not throw any error if item doesn't exist in list.")
A = {19, 22, 24, 20, 25, 26} 
B = {19, 22, 20, 25, 26, 24, 28, 27} 
#all set operation can be performed in set: union(), intersection()
print("\nUnion of A and B sets: ",A.union(B))
print("Intersection of A and B sets: ",A.intersection(B))
#issubset() returns true if it is subset of other else false
print("A is Subset of B? ",A.issubset(B))
#to check is A and B are disjoint sets ( no elements in common)
print("A and B are disjoint sets? ",A.isdisjoint(B))
print("(AUB) AND (BUA): ",(A.union(B)).intersection(B.union(A)))
#checking symmetric differece .. return the extra elements of set A that are not in B
print("Symmetric Difference of A with B: ",A.symmetric_difference(B))
#clear() clear/ delete all elements from set
A.clear()
B.clear()
print("After clear Set A values: ", A,"\tSet B values: ",B)

age = [22, 19, 24, 25, 26, 24, 25, 24] 
print("\nage list: ",age)
age_set = set(age)
print("set of ageslist: ", age_set)
print("Length of age list: ", len(age), "\nLength of age set",len(age_set))

Length of Set it_companies: 7
it_companies:  {'Amazon', 'Google', 'Microsoft', 'Twitter', 'Apple', 'Oracle', 'IBM', 'Facebook'}
it_companies after update:  {'Microsoft', 'Facebook', 'Google', 'Twitter', 'Salesforce', 'Wipro', 'IBM', 'Cognizant', 'Apple', 'Oracle', 'Amazon', 'LinkedIn'}
{'Microsoft', 'Facebook', 'Google', 'Twitter', 'Salesforce', 'Wipro', 'IBM', 'Cognizant', 'Apple', 'Oracle', 'Amazon'}

Difference between Remove() and Discard(): Discard() method is different from the remove() method, because the remove() method will throw an error if the specified item is not present in list, whereas the discard() method will not throw any error if item doesn't exist in list.

Union of A and B sets:  {19, 20, 22, 24, 25, 26, 27, 28}
Intersection of A and B sets:  {19, 20, 22, 24, 25, 26}
A is Subset of B?  True
A and B are disjoint sets?  False
(AUB) AND (BUA):  {19, 20, 22, 24, 25, 26, 27, 28}
Symmetric Difference of A with B:  {27, 28}
After clear Set A values:  set() 	Set B values: 

In [6]:
#Question 5
from math import pi
radius_of_circle = 30
_area_of_circle_ = pi * radius_of_circle **2
print("Area of a circle = ",_area_of_circle_," meters square")
_circum_of_circle_ = 2 * pi * radius_of_circle
print("Circumference of a circle = ",_circum_of_circle_, ' meters')

_radius_of_circle_ = float(input("Enter radius of circle: "))
_area_of_circle_ = pi * _radius_of_circle_ **2
print("Area of a circle = ",_area_of_circle_," meters square")

Area of a circle =  2827.4333882308138  meters square
Circumference of a circle =  188.49555921538757  meters
Enter radius of circle: 10
Area of a circle =  314.1592653589793  meters square


In [7]:
#Question 6
print("I am a teacher and I love to inspire and teach people")
set_words = set(("I am a teacher and I love to inspire and teach people".split(" ")))
print("Number of Unique words: ",len(set_words), set_words)

I am a teacher and I love to inspire and teach people
Number of Unique words:  10 {'and', 'teach', 'to', 'inspire', 'teacher', 'love', 'people', 'I', 'a', 'am'}


In [8]:
#Question 7
text = "\033[1m Name \t  Age \tCountry City\n Asabench 250 \tFinland Helsinki\033[0m"
print(text)

 Name 	  Age 	Country City
 Asabench 250 	Finland Helsinki


In [9]:
#Question 8
radius = 10 
area = 3.14 * radius ** 2 
# using 'f' we can format the data. %.0f will give data without any decimals, %.2f displays until 2 decimals
print("The area of a circle with radius",radius,"is %.0f" %area, "meters square.")

The area of a circle with radius 10 is 314 meters square.


In [10]:
#Question 9
#1lb = 0.453592kg
number_of_students = int(input("Enter number of students: "))
weight_of_students_lbs = list() #to store weights in lbs
weight_of_students_kgs = list() # to store weights in kgs

for each in range(number_of_students):
    weight_lb = int(input("Enter weight of {} student in lbs: ".format(each+1)))
    weight_of_students_lbs.insert(each, weight_lb)
    #converting lbs to kg and adding to seperate list
    weight_kg = float("%.2f" %(weight_lb*0.453592))
    weight_of_students_kgs.insert(each, weight_kg)
    
print("weight of students in lbs: ",weight_of_students_lbs)
print("weight of students in kgs: ",weight_of_students_kgs)


Enter number of students: 4
Enter weight of 1 student in lbs: 150
Enter weight of 2 student in lbs: 155
Enter weight of 3 student in lbs: 145
Enter weight of 4 student in lbs: 148
weight of students in lbs:  [150, 155, 145, 148]
weight of students in kgs:  [68.04, 70.31, 65.77, 67.13]


In [11]:
#Question 10
import numpy as nm   
import pandas as pd 
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import confusion_matrix 

X= nm.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
print("Dataset with total 8 points: \n",X,"\n Size: ",len(X))
y = nm.array([0,0,1,1,1,0,0,0])
print("\nClass label for the datasetX  Y:",y)
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.50, random_state=0,shuffle=False ) 
print("\nTraining Data X: \n", x_train)
print("\nTraining Data label Y:", y_train)

#feature Scaling-used to normalize the range of independent variables or features of data. .
#i.e.to standardize the data prior to performing classification 
stand_scalar= StandardScaler()    
x_train= stand_scalar.fit_transform(x_train)    
x_test= stand_scalar.transform(x_test) 

#Initialising KNN Classifier with value 3
classifier= KNeighborsClassifier(n_neighbors=3)  
#Fitting the data to classifier
classifier.fit(x_train, y_train)
#Predict Labels for x-test data
y_pred= classifier.predict(x_test) 
print('\nPredicted Classs labels for testing data Y:',y_pred)
     
#Confusion matrix with tested data
confusion_matrix_result = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix\n",confusion_matrix_result)

#total P+N can be calculated using sum(sum(conf_matrix))
total_value = sum(sum(confusion_matrix_result))
#Accuracy TN+TP / P+N
accuracy=(confusion_matrix_result[0,0]+confusion_matrix_result[1,1])/total_value
print ('\nAccuracy : ', accuracy)

#Sensitivity TP/(TP+FN)
sensitivity = confusion_matrix_result[1,1]/(confusion_matrix_result[1,0]+confusion_matrix_result[1,1])
print('Sensitivity : ', sensitivity )

#Specificity TN/(TN+FP)
specificity = confusion_matrix_result[0,0]/(confusion_matrix_result[0,0]+confusion_matrix_result[0,1])
print('Specificity : ', specificity)


Dataset with total 8 points: 
 [[ 1  0]
 [ 2  0]
 [ 3  0]
 [ 6  0]
 [ 6  0]
 [ 7  0]
 [10  0]
 [11  0]] 
 Size:  8

Class label for the datasetX  Y: [0 0 1 1 1 0 0 0]

Training Data X: 
 [[1 0]
 [2 0]
 [3 0]
 [6 0]]

Training Data label Y: [0 0 1 1]

Predicted Classs labels for testing data Y: [1 1 1 1]

Confusion Matrix
 [[0 3]
 [0 1]]

Accuracy :  0.25
Sensitivity :  1.0
Specificity :  0.0


# 